### ISSUE TITLE
Change project and package name to "cordova-background-geolocation-plugin"

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-background-geolocation-plugin#12]
Change all references to the project and package names to "cordova-background-geolocation-plugin".

- [x] Package name in `package.json`
- [ ] Package name in Android metadata
- [ ] Package name in iOS metadata
- [x] Repository name
- [x] References in documentation

**Comment by RaddishIoW** [comment]
@HarelM We need to make sure that any references to the plugin in the metadata for the platforms is updated before we publish.
I *think* that there's nothing in the iOS project files that needs changing, but I'm not sure about the Android files. I'm going to be busy this eve, so if you could take a quick look before you publish tonight and make sure I haven't missed anything, then close this out?

**Comment by HarelM** [comment]
Sure, I'll take a look. Do you want me to merge all the PRs?

**Comment by RaddishIoW** [comment]
I don't think any of them are needed for this release, so no.

**Comment by HarelM** [comment]
I looked in the project and didn't see more things that needs to be changed, I think.
We can change the Java namespaces and folders to reduce all the extra complexity of finding the java files but I'm not sure how useful it is and it will also remove the "credit" to people who started this plugin and codebase.
I'm not sure how useful it will be so I think it not mandatory/important. Having said that, I'm not against it either.
I'm not sure, but I think this issue can be closed...?

**Comment by HarelM** [comment]
Just found another location which I think explains why I thought adding a "@company" to the plugin does not work - the plugin that we forked from had used the original id "cordova-plugin-background-geoloaction" and not an id "@company" so this might explain why there were so many issues with the name, the npm package and everything else.
In any case, I'll push a commit to fix this now and create another npm package "rc.2".
Sorry for all the mess...

**Comment by RaddishIoW** [comment]
Yep, I agree, I think we should probably leave the java namespaces alone - at least for now - like you suggest.
Yeah, let's close this issue then. If there are any further changes we need to make we can create specific issues for those.
