### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by HarelM** [HaylLtd/cordova-background-geolocation-plugin#15]
## Feature Request

Seems that most updated plugins support AndroidX.
As far as I understand this is a breaking change in terms of the plugin (meaning you either support the old way or the new way) so I would avoid this change in a minor release.
I'm still not sure what needs to be done in order to support this and what's the status of the other community plugins. If most modern plugins already support this then it should be a high priority for next major release, but if not then it can wait.
I currently don't use AndroidX in my project since I think not all the plugins support this, but I need to check...

**Comment by RaddishIoW** [comment]
Cordova have released Android 10.0.0, which requires AndroidX support.
https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html

They cite the [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) as a way of migrating for projects still using the old support libs.

**Comment by RaddishIoW** [comment]
- [ ] Investigate what is needed to migrate to AndroidX support

**Comment by HarelM** [comment]
@RaddishIoW Let me know if you want me to help, I'm working extensively on MapLibre-gl these days but if you need me to look at something or help out let me know.
I know that the following plugin had made the change from android to androidX:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent#readme
These are the relevant commits, I think:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/ef584403a952b25ea71f0eda984921928322a9cd
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/567c0f8ce6ba830d6cc2bd98dfb9030c233524d2
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/61ed2cad5a6be7b71ea48d89a11ed691a32c2e6e

The first one might not be needed in case cordova-android is defaulting to androidX, maybe, not sure...
Good luck!

**Comment by HarelM** [comment]
@RaddishIoW did you get around to doing this?
I'm trying to migrate now to cordova-android@10 and this is the main plugin that fails compilation.
Everything I tried that did not require to change the code here does not seem to work.
Let me know what's the status of this.
As a side not, it might be better to move the files a bit in order to have all the files under the same namespace. currently when the build fails it's unclear that the files belong to this plugin as they are scattered around in all kind of namespace.
Not entirely related to this issue though...

**Comment by HarelM** [comment]
Opening the android folder in android studio and clicking refactor migrate to androidX seems to do most of the heavy lifting.
I've created a branch called androidX to allow testing this and fixing what needs to be fixed.
I'll report back here after I successfully manage to migrate my project to androidX.

**Comment by RaddishIoW** [comment]
Hi @HarelM, sorry for the late reply - I've been snowed-under in other things for a few weeks, and just haven't had the bandwidth to even look at GitHub.
Glad you managed to get this sorted! I'll update when I get a chance and check it with my app.

This wasn't a major issue for me, as I was using a cordova plugin to convert to AndroidX on-the-fly...

So I think we can close this issue now, yeah?

**Comment by HarelM** [comment]
This plugin didn't work for me, I'm not sure why, but it was a good incentive :-)
Yes, closing...
