### ISSUE TITLE
Use Github actions to automate npm publish

### ISSUE THREAD

**Issue by HarelM** [HaylLtd/cordova-background-geolocation-plugin#17]
I'm still new to this, so I might need a little help here but it would be extremely helpful if we could automate testing and releasing of npm packages by using Github actions.

The way I see it:
If we create a tag on master branch it will create an npm package with the relevant tag
On any commit to master tests and lint will run (assuming there are tests and lint is defined)

The first one is the most important from my point of view to reduce manual work that tends to be error prone...

**Comment by HarelM** [comment]
I'll try this plugin:
https://github.com/marketplace/actions/npm-publish

**Comment by HarelM** [comment]
@RaddishIoW seems like I can't add secrets to this repo, can you check my permissions please?

**Comment by RaddishIoW** [comment]
Looks like you need to be an admin to see secrets, so you are now an admin! :) Use your powers wisely ;)

**Comment by RaddishIoW** [comment]
Are you going to use your account to push to npm? I haven't looked at this yet, but I guess the package is pushed to npm from this GitHub action?

**Comment by HarelM** [comment]
Yes, seems like there's a template to cover both github packages and npm. I'll add my token to the secrets and use this to try and publish later today.

**Comment by RaddishIoW** [comment]
I've set the version number to 1.0.0-rc.1 already, so we can use that to publish a first go...

**Comment by HarelM** [comment]
OK, seems like the first version is now in npm! :-)
https://www.npmjs.com/package/cordova-background-geolocation-plugin
All I did in order to create it was to create a github release which triggered the action.
I gave the tag and the release the same name/title as the version and added some basic description.
publishing to github packages repository (GPR) failed though, it might be because there was no npm repository when this action started. It might work in the next version, but form my point of view it's not mandatory - the most important part of this issue is the publishing to npm so in theory, if the gpr continues to not work we could simply remove it from the action yml file.
I'll go ahead and try to use the published package in my repo to see if there are any issues.
I'll report here if I find any, I hope it will go smooth. :-)

**Comment by HarelM** [comment]
OK, According to this issue:
https://github.com/actions/starter-workflows/issues/471
Seems like GPR needs a scope (i.e. @Company) which this package doesn't have and is not intended to have and also the comments on the issue says that it's probably better to have just one.
I'll be removing the GPR action for both simplicity and practicality...
