### ISSUE TITLE
Move platform specific sub modules into main repository

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-background-geolocation-plugin#22]
The platform specific sub modules should be brought into the main repository to make it easier to maintain.

**Comment by RaddishIoW** [comment]
fixed in 2c934f2

**Comment by HarelM** [comment]
@RaddishIoW are you sure this is resolved?
I can't see the required folder (common folder for android for example) in this repo anymore and it also seems that when trying to install the package I created in npm it fails because the files are missing...
Let me know if there's anything I can do to help...

**Comment by RaddishIoW** [comment]
Hmmm... I *thought* it went a bit too smoothly! I read up on how to remove submodules and it seemed complicated, but I found a command in my git client to just "do it", and it seemed to work... I have those folders/files in my checkout of the repo, and from what I could see on GitHub they seemed to still be there.

What I might do is try exporting those submodule repos separately and add them to my checkout and see if git recognises them as new files to add to the repo, because they didn't show as new after removing the submodules...

**Comment by RaddishIoW** [comment]
OK, just pushed a commit with the common files back in - give that a go and close this if it works. :)

**Comment by HarelM** [comment]
I'll create rc.3 and try it out.
The files seems to exist now.
We'll probably need to clean this up a bit since it has all kind of gradle, ci, readme which is probably not needed when everything is in the same repo, but we can do it later on... It's not urgent.

**Comment by RaddishIoW** [comment]
I'll give rc.3 a go this eve if I get a chance and see if it works as a drop-in replacement.
Any chance you can add me as a maintainer on NPM for the package?

**Comment by HarelM** [comment]
Sure, what's your npm account name?
As a side note, you don't need to do anything with npm as the github action takes care of everything.

**Comment by RaddishIoW** [comment]
raddishiow 👍🏼

**Comment by HarelM** [comment]
I've added you. It shows that you require 2FA, I don't know if you can change it or not, but I guess that for now it would do...

**Comment by HarelM** [comment]
I've tested rc.3 in a too optimistic way - i.e. replaced the package in my repository (branch) and created an app using my CI and uploaded it to internal testers.
The app crashes :-(
So rc.3 is probably not good.
I'll try and see if I can debug the app to see what's wrong...
Not sure it is related to this issue specifically, but it might...
You can see the commits linked to this issue:
https://github.com/IsraelHikingMap/Site/issues/1427

**Comment by RaddishIoW** [comment]
I'm seeing it crash too on a quick android build of my app.
Haven't had a chance to look at it yet, but I'll check when I get a chance.

**Comment by HarelM** [comment]
This is the exception I'm getting:
`java.lang.RuntimeException: Unable to get provider com.marianhello.bgloc.data.provider.LocationContentProvider: android.content.res.Resources$NotFoundException: String resource ID #0x0`
Probably related to the strings I changed...
I'll see if I can understand what caused this before I revert the string changes I made...

**Comment by HarelM** [comment]
OK, I understand what went wrong - I renamed all the things related to "mauron85" before the submodules fix so I didn't have all the files when I searched and I didn't do it again after the submodules fix.
I'll rename, commit, push and publish.

**Comment by HarelM** [comment]
I've published 1.0.0-rc.4.
From a very initial check, it seems like it is working fine (or at least it's not crashing).
I'll update my app with this version and try it out later tonight or tomorrow morning.
I'm leaning towards closing this issue as it seems like the problem we are facing are not related to missing files that were in the submodules.
Unless you would like to keep this issue open in order to do the submodules clean up as part of this issue.
Your call...

**Comment by HarelM** [comment]
Tracking and background recording seems to be working in my app with rc.4.
I think it's safe to say that it's working as expected.
