### ISSUE TITLE
[Android] Fresh install fails on resources (icon) not found

### ISSUE THREAD

**Issue by HarelM** [HaylLtd/cordova-background-geolocation-plugin#23]
**Describe the bug**
When adding the plugin to a cordova project the android build fails due to missing icon

**To Reproduce**
`cordova plugin add <this plugin>`
`cordova build android`

**Expected behavior**
Should work

**Desktop (please complete the following information):**
 - OS: [Android]

**Additional context**
changing the `@mipmap/icon` to `@mipmap/ic_launcher` solves this issue.
Might be only my environment though, not sure, but it's not a great developer experience.
Also the icon that exists is a default one and not the app icon.
The build has warnings.

I would like to address all these issues related to icon definition in this issue, either by documentation or by proper cordova intallation/build code.

**Comment by HarelM** [comment]
I think this issue is the same as:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/553
Which was also reported here:
https://github.com/apache/cordova-android/issues/678
I think the solution to this issue is simply change the default parameter value from `icon` to `ic_launcher` and writing in the documentation that this plugin supports Cordova 8.x and above.

**Comment by RaddishIoW** [comment]
I'm going to be working on another Android issue today, so I'll check this out too.

**Comment by HarelM** [comment]
Go ahead. I think the only change that is needed is changing the default value of the parameter, the rest of the issues I saw in the build are not related to this plugin, I think...

**Comment by RaddishIoW** [comment]
Right, yep - lets make sure that we're targeting only Cordova Android >= 8.0 and API >= 26. I'll add these checks to the plugin, and modify the docs to match.

**Comment by HarelM** [comment]
Go ahead. The docs still has an example of old config style which is inside config.xml, this is no longer relevant as it moved to package.json. Worth fixing this too I believe...

**Comment by RaddishIoW** [comment]
Ah right - this section?
```
<plugin name="cordova-background-geolocation-plugin" spec="cordova-background-geolocation-plugin@~1.0.0">
  <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
  <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
  <variable name="ICON" value="@mipmap/ic_launcher" />
  <variable name="SMALL_ICON" value="@mipmap/ic_launcher" />
  <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking " />
  <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" /> 
</plugin>
```

**Comment by HarelM** [comment]
Yup. :-)
