### ISSUE TITLE
Missing org.apache.http.legacy library dependency

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-background-geolocation-plugin#24]
**Describe the bug**
On a fresh install of the plugin, android builds fail with the error:
`error: package org.apache.http does not exist import org.apache.http.HttpResponse` etc.

This is due to a missing library dependency.

**To Reproduce**
1. Install the plugin in a cordova project
2. Build for android
3. See error

**Expected behavior**
The plugin registers all required dependencies on install.

**Additional context**
The app's `AndroidManifest.xml` requires the following to be added:
`<uses-library android:name="org.apache.http.legacy" android:required="true" />`

The app's `build.gradle` requires the following to be added:
`useLibrary 'org.apache.http.legacy'`

**Comment by HarelM** [comment]
Is this due to submodule changes or existed always? I don't think I have build issues. Might be a configuring issue I don't have I guess...?

**Comment by RaddishIoW** [comment]
I remember having this issue when I first installed the @mauron85 version, and luckily had the google searches still in my browser history for how to solve it!
It might be that you have another plugin that uses this legacy http already? I don't think it will harm anything to have this in our plugin, but I'm prepared to be wrong! :)

**Comment by HarelM** [comment]
I might have a plugin that has this as a dependency (Although I can't think of one but I haven't looked in all of them).
In any case, if this is missing it and causes build failures it's needed. No argue here.
I think we should consider creating an example super simple project that uses this plugin for this exact reason - to make sure that an app with only this dependency doesn't fail to build...

**Comment by RaddishIoW** [comment]
Great idea - we can use it as a testbed. We could then get GitHub Actions to check the latest build of the plugin with it too?

**Comment by HarelM** [comment]
Exactly! I tend to say that it should be as a separate repository, what do you think?

**Comment by HarelM** [comment]
We could also probably clone this one?
https://github.com/mauron85/cordova-plugin-background-geolocation-example

**Comment by RaddishIoW** [comment]
Yeah, I'd say a separate repo, like the one you linked... Might be worth starting from scratch? I haven't looked at the old one, but I can imagine it might be out of date in regard to other dependencies, and we should really know what's going on in it.
Shall I create a blank repo for it? I think it makes sense to have it live on the same GitHub namespace?

**Comment by HarelM** [comment]
I'll open a separate issue so we can define and implement this.
